apiVersion: apps/v1
kind: Deployment
metadata:
  name: dfx-tag-generator
  namespace: dfx
  labels:
    app: dfx-tag-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dfx-tag-generator
  template:
    metadata:
      labels:
        app: dfx-tag-generator
    spec:
      containers:
        - name: dfx-tag-generator
          image: ghcr.io/alexmchugh1/ot-edge-asset-tag-generator:latest
          ports:
            - containerPort: 9092
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /
              port: 9092
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 9092
            initialDelaySeconds: 3
            periodSeconds: 5
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
