apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: ghcr.io/alexmchugh1/ot-edge-asset-tag-generator
  newName: ghcr.io/alexmchugh1/ot-edge-asset-tag-generator
  newTag: sha-375cffa
